### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by H-QueerCoded** [Red-Studio-Ragnarok/Alfheim#32]
## Describe the bug

Game crashes when launched with Alfheim in my modpack. Crash report mentions an injector related to Optifine but I don't have Optifine installed. Tried reproducing the bug in another instance with Alfheim and the mods mentioned in the mixin stacktrace (UniversalTweaks, NormalASM) but the issue wasn't replicated. Also tried Alfheim in combination with all the performance/optimization/fix mods I have and was still unable to reproduce the issue.

## Reproducibility
- [ ] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.

## Expected behavior

Game launches fine as it does when launched with Phosphor 0.2.7 + Phosphor Crash Fix 1.0.0

## Logs or/and crash reports

[Crash Report](https://api.mclo.gs/1/raw/irZMUN2)

## Versions

- Red Core 0.5.1 
- Alfheim 1.2
- BetterFPS 1.4.8
- Config Anytime 1.0
- MixinBooter 8.9
- NormalASM 5.18
- Universal Tweaks 1.8.0
- VintageFix 0.3.3
- RandomPatches 1.12.2-1.22.1.10
- Forge: 1.12.2 - 14.23.5.2860
- Java: jre1.8.0_301
- Custom Agents: serializationisbad-1.5

## Specification:

- OS: Windows 11
- CPU: AMD Ryzen 9 5900HS
- GPU: NVIDIA 3070 Mobile/Laptop
- RAM Allocated: 4GB

**Comment by H-QueerCoded** [comment]
an update: I was also able to load the pack using hesperus

**Comment by Dark-Hunter666** [comment]
### Crash
I have the same problem minecraft crashes on startup with code 1, only after adding _Alfheim._

### Minecraft startup log
2024-01-18 16:45:21,041 main ERROR appender Console has no parameter that matches element Policies

[16:45:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:45:21] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:45:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:45:21] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[16:45:21] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_392-internal, running on Linux:aarch64:Android-13, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
[16:45:21] [main/INFO]: Searching /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods for mods
[16:45:21] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [1.12.2]+SecurityCraft+v1.9.8.jar
[16:45:21] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from _supermartijn642corelib-1.1.16a-forge-mc1.12.jar
[16:45:21] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Alfheim-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:45:21] [main/ERROR]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_392-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_39
2-internal]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_392-internal]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: zone.rong.mixinbooter.IEarlyMixinLoader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_392-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_392-internal]
	at java.lang.Class.forName(Unknown Source) 
~[?:1.8.0_392-internal]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_392-internal]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_392-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_392-internal]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_392-internal]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModMan
ager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 5 more
Exception in thread "main" [16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:45:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1
I/jrelog  (13117): Going to free args
I/jrelog  (13117): Free done

**Comment by H-QueerCoded** [comment]
My crash went away after the following process:

1. New intsance without symlinks (which I had previously used) but same mod list, config, etc
2. Update Universal Tweaks to 1.9.0
3. Update JAOPCA
4. Add Nothirium
5. Update VintageFix to 0.4.0
6. Switch Hesperus for Alfheim

Can't say exactly which step solved the problem though.

**Comment by Desoroxxx** [comment]
@Dark-Hunter-04 you forgot to add MixinBooter, you may have forgoten Red Core

**Comment by Dark-Hunter-04** [comment]
@H-QueerCoded
Sorry but I'm new to the world of IT, anyway I tried to do what you told me but without success... I am using pojavlauncher from my phone (Xiaomi Redmi Note 11 Pro 5g) Now I use it Phosphor instead of Alfheim
